markdown: kramdown
name: Civic Tech DC
url: https://civictechdc.org
title: Civic Tech DC
description: "We are a non-partisan, non-political group of volunteer civic hackers working together to solve local issues and help people engage with the city."
encoding: utf-8
timezone: America/New_York
plugins:
  - jekyll-redirect-from
future: true
baseurl: ""

collections:
  projects:
    output: true

exclude:
  - /node_modules/
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - npm-debug.log
  - /sass
